---
- name: "Change 'save_handler' in www.conf"
  ansible.builtin.lineinfile:
    path: "/etc/php-fpm.d/www.conf"
    regexp: "^php_value(.*)session.save_handler(.*)files"
    line: "php_value[session.save_handler] = memcached"

- name: "Change 'save_path' in www.conf"
  ansible.builtin.lineinfile:
    path: "/etc/php-fpm.d/www.conf"
    regexp: "^php_value(.*)session.save_path(.*)"
    line: "php_value[session.save_path] = /var/run/memcached/memcached.sock"