---
- import_tasks: prepare-www-conf.yml
  notify:
    - "Restart php-fpm"

- import_tasks: prepare-php-ini.yml
  notify:
    - "Restart php-fpm"

- name: "Copy configuration for SOCK mode"
  ansible.builtin.copy:
    src: "files/etc/nginx/conf.d/default.conf"
    dest: "/etc/nginx/conf.d/default.conf"
  notify:
    - "Restart nginx"

