---
- name: "Create a directory 'sites-enabled'"
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled"
    state: directory

- name: "Copy new nginx.conf"
  ansible.builtin.copy:
    src: "files/etc/nginx/nginx.conf"
    dest: "/etc/nginx/nginx.conf"

- name: "Remove default.conf"
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
